TELEGRAM_API_KEY = 'TELEGRAM_API_KEY_HERE'

FEEDBACK_RECEIVER_CHAT_ID = 'FEEDBACK_RECEIVER_CHAT_ID_HERE'

DB_NAME = 'DB_NAME_HERE'
DB_USER = 'DB_USER_HERE'
DB_USER_PASSWORD = 'DB_USER_PASSWORD_HERE'
DB_HOST = 'DB_HOST_HERE'
DB_PORT = 'DB_PORT_HERE'

DEBUG = False

try:
    from settings_local import * # NOQA
except Exception:
    print('Local settings can not be found.')
