# Generated by Django 2.1.1 on 2018-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
