services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: jira_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  django:
    build:
      context: ../..
      dockerfile: conf/docker/Dockerfile_django
    command: gunicorn django_microservice.wsgi:application --bind 0.0.0.0:8000
    env_file: ../../.env
    depends_on:
      - db
    expose:
      - 8000
    restart: always

  tg-bot:
    build:
      context: ../..
      dockerfile: conf/docker/Dockerfile_bot
    env_file: ../../.env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
